### ISSUE TITLE
undefined method 'implementation' for HTTP::CookieJar::AbstractStore:Class

### ISSUE THREAD

**Issue by maia** [sparklemotion/http-cookie#6]
I found the following error in my heroku logfiles:

```
NoMethodError: undefined method `implementation' for HTTP::CookieJar::AbstractStore:Class
/app/vendor/bundle/ruby/2.2.0/gems/http-cookie-1.0.2/lib/http/cookie_jar.rb:38:in `get_impl'
/app/vendor/bundle/ruby/2.2.0/gems/http-cookie-1.0.2/lib/http/cookie_jar.rb:74:in `initialize'
/app/vendor/bundle/ruby/2.2.0/gems/mechanize-2.7.3/lib/mechanize/http/agent.rb:135:in `new'
/app/vendor/bundle/ruby/2.2.0/gems/mechanize-2.7.3/lib/mechanize/http/agent.rb:135:in `initialize'
/app/vendor/bundle/ruby/2.2.0/gems/mechanize-2.7.3/lib/mechanize.rb:182:in `new'
/app/vendor/bundle/ruby/2.2.0/gems/mechanize-2.7.3/lib/mechanize.rb:182:in `initialize'
```

Unfortunately I did not log the uri that was queried by my rake task, and the problem did not occur in the following hours. I still hope it's enough info to find the culprit.

**Comment by carsonreinke** [comment]
I have received this error also, randomly.

**Comment by perlun** [comment]
I have also been seeing this appearing on Sentry. Unsure of what is triggering it.

**Comment by perlun** [comment]
I saw this in the logs again now. My suspicion is something related to https://github.com/sparklemotion/http-cookie/commit/bafb83fc060b6fac9fe1a506477206ca3a4fbf63. We apparently auto-load these files, and in my case, the gem is being used from multiple threads concurrently - it _could_ be a glitch in the gem or MRI related to the auto-loading.

@knu - would it be OK with you to skip the autoloading and require the abstract_store unconditionally instead? If so, I'll gladly submit a patch to hopefully solve this issue.

**Comment by JasonLunn** [comment]
We still see this issue today, in `1.0.3`, on JRuby, so it doesn't appear to be MRI specific or limited to version `1.0.2` that was initially reported. Has anyone developed a workaround in the two years since this was filed?

**Comment by perlun** [comment]
@JasonLunn Not that I know of. I _suspect_ that loading files late (when they are needed) have race conditions. So loading everything at once, on startup, could work - if you find a working strategy, please post the suggestions here so we can apply it (and hopefully submit a PR to the gem for it to get fixed properly).

**Comment by grosser** [comment]
seeing the same ... updating to latest in hope that fixes anything ... was running the same app for months and after a restart this popped up ...

**Comment by perlun** [comment]
The project seems unfortunately quite abandoned at the moment. 😢 No new commits since December, and 5 open pull requests.

Do we have anyone with time and energy to fork it and maintain it? Or better yet, contact the original author (@sparklemotion) to be added as a maintainer here?

**Comment by nakilon-idwell** [comment]
> The project seems unfortunately quite abandoned

I'm dealing with mechanize and its source code just told me I should use this library ..\

**Comment by Nakilon** [comment]
> The project seems unfortunately quite abandoned

I'm dealing with mechanize and its source code just told me I should use this library ..\

**Comment by grosser** [comment]
eager load might help ... I'll report back if I see it again after using this 🤷‍♂ 
```ruby
# eager load http-cookie gem to avoid random error
# https://github.com/sparklemotion/http-cookie/issues/6
cookie = $LOAD_PATH.detect { |l| l.match?(/\/http-cookie-\d/) }
Dir["#{cookie}/**/*.rb"].grep_v(/mozilla_store/).each { |f| require f.sub("#{cookie}/", "").sub(".rb", "") }
```

**Comment by grosser** [comment]
eager load confirmed working :)

**Comment by headius** [comment]
I'm not sure it's related, but I found a similar bug in the `AbstractStore` class caching logic that can expose incomplete classes when called across threads: https://github.com/sparklemotion/http-cookie/issues/27

**Comment by godfat** [comment]
I concur that eagerly loading it will fix the problem. I had workaround almost 4 years ago and it never happened again:

* https://github.com/godfat/rest-core/commit/8b85837db400f29fc8df419a3b761ddd130ed581
* https://github.com/godfat/rest-core/commit/4ed06367675f2ecddf084abb51c00931d848de28 (for http-client)

**Comment by godfat** [comment]
@jordan-thoms You might be interested about working around this problem in http-client. I found just `HTTPClient.new` and throw it away while loading the application works the best: https://github.com/godfat/rest-core/commit/4ed06367675f2ecddf084abb51c00931d848de28

**Comment by grosser** [comment]
FYI since update my example above, files need to be sorted before getting required or you get weird errors on some systems
